repos:

-   repo: https://github.com/ambv/black
    rev: 21.6b0
    hooks:
    - id: black
      language_version: python3.8

-   repo: https://github.com/pycqa/isort/
    rev: 5.6.4
    hooks:
    - id: isort
      language_version: python3.8
