on:
  workflow_dispatch: {}
  schedule:
  - cron: "40 5 * * *"

name: pip-compile
jobs:
 pip_compile:
   name: pip-compile
   runs-on: ubuntu-latest
   steps:
     - name: Setup Python
       uses: actions/setup-python@v2
       with:
         # TODO: multi-version support
         python-version: 3.8
     - name: pip-compile
       uses: technote-space/create-pr-action@v2
       with:
         EXECUTE_COMMANDS: |
           pip install pip-tools
           pip-compile -U --generate-hashes test-requirements.in
           
         COMMIT_MESSAGE: 'chore: scheduled pip-compile'
         COMMIT_NAME: 'GitHub Actions'
         COMMIT_EMAIL: 'noreply@github.com'
         PR_BRANCH_PREFIX: deps/
         PR_BRANCH_NAME: 'pip-compile'
         PR_TITLE: 'chore: scheduled pip-compile'
         AUTO_MERGE_THRESHOLD_DAYS: 1
         PR_BODY: '## Update dependencies

  This is a scheduled update of Python dependencies within this repo managed by pip-compile.

  This change will be submitted automatically after 1 day(s) if all checks have succeeded.'
